# conda env create -f environment.yml
# conda activate vrr
name: vrr
channels:
    - pytorch
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - numpy
    - pandas
    - matplotlib
    - pip
    - tqdm
    - pytorch
    - torchvision
    - torchaudio
    - cudatoolkit
    - pip:
        - configargparse
        - imageio
        - imageio-ffmpeg
        - scipy