117682_assemble:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 100
    - 1
    - 100
    translate:
    - 0
    - 2
    - 0
  nearClip: 0.1
  toworld:
    origin:
    - 3
    - -1
    - 3
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1

cloth:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 1
    - 10
    translate:
    - 0
    - -1
    - 0
  nearClip: 0.1
  toworld:
    origin:
    - 0.5
    - 1.8
    - 2.8
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 1
    - 0

pants:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 100
    - 1
    - 100
    translate:
    - 0
    - -1
    - 0
  nearClip: 0.1
  toworld:
    origin:
    - 0.5
    - 2.5
    - 3.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 1
    - 0

room1:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 100
    - 1
    - 100
    translate:
    - 0
    - -1
    - 0
  nearClip: 0.1
  toworld:
    origin:
    - 0.5
    - 2.5
    - -3.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 1
    - 0

125611494287978_ShirtNoCoat:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - 0
    - 4.0
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
125611494690178_ShortPants:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - 0
    - 5.0
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
125611504997669_LongCoat:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - 0
    - 3
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
131971_bird_cage:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 100
    - 1
    - 100
    translate:
    - 0
    - 2
    - 0
  nearClip: 0.1
  emitter:
    origin:
    - -4
    - -4
    - 20
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
    color:
    - 6
    - 6
    - 6 
  toworld:
    origin:
    - -2
    - -3.5
    - 1
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'252119':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 100
    - 1
    - 100
    translate:
    - 0
    - -2
    - 0
  nearClip: 0.1
  emitter:
    origin:
    - 4
    - 4
    - 20
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
    color:
    - 6
    - 6
    - 6 
  toworld:
    origin:
    - 2.5
    - 2.5
    - 1.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'313444':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -5
    - 0
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'316358':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 3
    - -5
    - 0
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'354371':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -5
    - 0
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'398259':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -5
    - 3
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
39878_protein:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 100
    - 1
    - 100
    translate:
    - 0
    - 10
    - 0
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -4
    - 2
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
41729_ship:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 100
    - 100
    - 1
    translate:
    - 0
    - 0
    - -10
  nearClip: 0.1
  toworld:
    origin:
    - -2.5
    - 1.5
    - 1.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'441708':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 100
    - 1
    - 100
    translate:
    - 0
    - 2
    - 0
  nearClip: 0.1
  emitter:
    origin:
    - -4
    - -4
    - 20
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
    color:
    - 6
    - 6
    -  6
  toworld:
    origin:
    - 1.5
    - -3.5
    - 1.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'44234':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 100
    - 1
    - 100
    translate:
    - 0
    - 2
    - 0
  nearClip: 0.1
  toworld:
    origin:
    - -2.5
    - -2.5
    - 2.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
47564_apple:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 100
    - 1
    - 100
    translate:
    - 0
    - 2
    - 0
  nearClip: 0.1
  toworld:
    origin:
    - -2
    - -2
    - -3.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'47984':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 3.5
    - -3.5
    - 2.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
51017_eight_desk:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 3
    - 3
    - -3
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'527631':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 3
    - -5
    - 2
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'53159':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -4
    - 2.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
53750_hilbert:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 100
    - 1
    - 100
    translate:
    - 0
    - -2
    - 0
  nearClip: 0.1
  toworld:
    origin:
    - 3
    - 3
    - 3
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'58168':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - 1
    - 4
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'64444':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 2
    - 3.5
    - 0.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'64764':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 1.5
    - -4
    - 0.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
67858_three_chair:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 3
    - -3
    - 3
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'68380':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - -3
    - 3
    - 3
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'68381':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -5
    - 1
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'72870':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -3
    - 1
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'72960':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -4.5
    - 1
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'73075':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - -4.5
    - 2.5
    - 0
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'75496':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -5.5
    - 0
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'75655':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -4
    - 3
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'75656':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -4
    - 3
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'75662':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -4
    - 3
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'75665':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -4
    - 3
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'76277':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -4
    - 3
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'77245':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -4
    - 3
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'78671':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -5
    - 2
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'79241':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 5
    - 0
    - 3
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'90889':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -4
    - 1
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'92763':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -4
    - 1
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'92880':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - -4
    - -2
    - 1
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'95444':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - -5
    - 0
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
'96481':
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - 0
    - 4
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
clockwork:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -1
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - 3.5
    - 3.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
lizard:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -1
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - 3.5
    - 3.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
stanford_armadillo:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - 0
    - -5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
stanford_bunny:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - 0
    - 5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
stanford_dragon:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 100
    - 1
    - 100
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - 0
    - 4
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
stanford_happy:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - 0
    - 5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
stanford_statuette:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - 0
    - 0
    - 5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
synthetic_room_1:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - -1
    - 2
    - -4
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 1
    - 0
synthetic_room_2:
  farClip: 1000
  fov: 30
  ground:
    scale:
    - 10
    - 10
    - 1
    translate:
    - 0
    - 0
    - -2
  nearClip: 0.1
  toworld:
    origin:
    - -1.5
    - 1
    - 3.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 1
    - 0
synthetic_room_3:
  farClip: 1000
  fov: 30
  nearClip: 0.1
  toworld:
    origin:
    - 1.5
    - 1
    - -3.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 1
    - 0
synthetic_room_4:
  farClip: 1000
  fov: 30
  nearClip: 0.1
  toworld:
    origin:
    - -1.5
    - 1
    - 3.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 1
    - 0
synthetic_room_5:
  farClip: 1000
  fov: 30
  nearClip: 0.1
  toworld:
    origin:
    - -1.5
    - 1
    - 3.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 1
    - 0
synthetic_room_6:
  farClip: 1000
  fov: 30
  nearClip: 0.1
  toworld:
    origin:
    - 1.5
    - 1
    - 3.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 1
    - 0
synthetic_room_7:
  farClip: 1000
  fov: 30
  nearClip: 0.1
  emitter:
    origin:
    - -4
    - 4
    - -20
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 0
    - 1
    color:
    - 6
    - 6
    - 6 
  toworld:
    origin:
    - -1.5
    - 1
    - -3.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 1
    - 0
synthetic_room_8:
  farClip: 1000
  fov: 30
  nearClip: 0.1
  toworld:
    origin:
    - -1.5
    - 1
    - 3.5
    target:
    - 0
    - 0
    - 0
    up:
    - 0
    - 1
    - 0
